#!/bin/bash

echo "=> Building the binary"

docker run --rm -v $(pwd):/usr/bin/app:rw niaquinto/gradle consultant-portal-frontend:clean consultant-portal-frontend:install_frontend consultant-portal-frontend:webjar consultant-portal-backend:clean consultant-portal-backend:build